
on:
  push:
    branches:
      - main

permissions:
  id-token: write 
  contents: write 
  pages: write    

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Build with Vite
        run: npm run build

      - name: Add .nojekyll file
        run: echo > dist/.nojekyll

      - name: Upload build artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist

      - name: Vite GitHub Pages Deployer
        uses: skywarth/vite-github-pages-deployer@v1.5.0
        with:
          public_base_path: /  # This is the base
          build_path: ./dist
          install_phase_node_env: dev
          build_phase_node_env: production
          package_manager: npm
          artifact_name: github-pages
          debug_mode: false
          working_path: ./
